version: "3"

services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-reactive-resume}

  app:
    image: amruthpillai/reactive-resume:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - storage_data:/srv/data/uploads
    depends_on:
      - mongo
    env_file:
      - ../../.env
    environment:
      # -- Database --
      DATABASE_URL: mongodb://mongo:27017/${MONGO_DATABASE:-reactive-resume}?directConnection=true&authSource=admin

      # -- Storage --
      STORAGE_PATH: /srv/data/uploads
      STORAGE_URL: ${PUBLIC_URL:-http://localhost:3000}/storage

volumes:
  mongo_data:
  storage_data: 